artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/mohitgupta-1O1/Kaggle-SMS-Spam-Collection-Dataset-/master/spam.csv
  local_data_file: artifacts/data_ingestion/data.csv
  


data_validation:
  root_dir: artifacts/data_validation
  data_tobe_validated: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  validated_data: artifacts/data_validation/validated_data.csv


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/validated_data.csv
  transformed_data_path: artifacts/data_transformation/transformed_data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/transformed_data.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  #test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  test_data_path: artifacts/model_trainer/train_test.pkl
  mlflow_uri: https://dagshub.com/Vasim-rgb/end_end_ml.mlflow
