name: CI/CD - Docker, DockerHub & Ngrok

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

    # 4️⃣ Push image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    # 5️⃣ Run the container locally on port 5000
    - name: Run Docker container
      run: docker run -d --name myapp-container -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    # 6️⃣ Install ngrok
    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok

    # 7️⃣ Auth ngrok
    - name: Authenticate ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    # 8️⃣ Start ngrok tunnel for port 5000
    - name: Start ngrok tunnel
      run: |
        nohup ngrok http 5000 > /dev/null &
        sleep 5
        curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'